// Code generated by "callbackgen -type GRID"; DO NOT EDIT.

package leven

import ()

func (inc *GRID) OnUpdate(cb func(value float64)) {
	inc.updateCallbacks = append(inc.updateCallbacks, cb)
}

func (inc *GRID) EmitUpdate(value float64) {
	for _, cb := range inc.updateCallbacks {
		cb(value)
	}
}
